# Generated by Django 3.0.2 on 2020-02-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200204_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='loginned',
            field=models.BooleanField(default=False),
        ),
    ]
