# Generated by Django 3.0.2 on 2020-02-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramuser_loginned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
