# Generated by Django 3.0.2 on 2020-02-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200206_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='name',
            new_name='login',
        ),
    ]
