# Generated by Django 3.0.2 on 2020-02-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20200206_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='user_id',
            new_name='tg_id',
        ),
    ]
