# Generated by Django 3.0.2 on 2020-02-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20200207_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acceed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
