# Generated by Django 3.0.2 on 2020-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20200208_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acceed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
