# Generated by Django 3.0.2 on 2020-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20200208_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='acceed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complited',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, None), (2, 'rejected'), (3, 'acepted'), (4, 'complited')], default=1),
        ),
    ]
