# Generated by Django 3.0.2 on 2020-02-14 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20200213_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('telegramuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.TelegramUser')),
            ],
            bases=('bot.telegramuser',),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2020, 2, 14)),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, None), (2, 'rejected'), (3, 'accepted'), (4, 'completed')], default=1),
        ),
    ]
