# Generated by Django 3.0.2 on 2020-02-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_taskmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='password',
        ),
    ]
