# Generated by Django 3.0.2 on 2020-02-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_remove_telegramuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(default='password', max_length=200),
        ),
    ]
