# Generated by Django 3.0.2 on 2020-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_telegramuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
