# Generated by Django 3.0.2 on 2020-02-17 10:02

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20200217_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='password',
            field=fernet_fields.fields.EncryptedCharField(max_length=100),
        ),
    ]
