# Generated by Django 3.0.2 on 2020-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20200217_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='tg_id',
            new_name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='login',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'rejected'), (3, 'accepted'), (4, 'completed')], default=1),
        ),
        migrations.DeleteModel(
            name='UserModule',
        ),
    ]
