# Generated by Django 3.0.2 on 2020-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20200220_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
