# Generated by Django 3.0.2 on 2020-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_auto_20200220_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
