# Generated by Django 3.0.2 on 2020-02-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_auto_20200221_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, '❌ rejected'), (3, '✅ accepted'), (4, '🤘 completed')], default=1),
        ),
    ]
