# Generated by Django 3.0.3 on 2020-02-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_auto_20200222_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskModule',
        ),
    ]
