# Generated by Django 3.0.3 on 2020-02-25 08:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_delete_taskmodule'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('tasks', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='telegramuser',
            managers=[
                ('telegram_users', django.db.models.manager.Manager()),
            ],
        ),
    ]
