# Generated by Django 3.0.3 on 2020-03-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_auto_20200225_1037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='telegramuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'rejected'), (3, 'accepted'), (4, 'completed')], default=1),
        ),
    ]
